### ISSUE TITLE
Issue with Import for ApplePass

### ISSUE THREAD

**Issue by viral-vora** [PrimedigitalGlobal/applepassgenerator#3]
I appreciate the work done to setup this wonderful library that helps Python developers to generate Apple Passes smoothly.

I found that inside client.py, the import is done by the following statement:
`from models import ApplePass`

But, there is no module with ApplePass inside applepassgenerator. I suggest the import should like the following because ApplePass belongs to models module:
`from applepassgenerator.models import ApplePass`

Please let me know if any more information is required.

**Comment by vaibhav-pdgt** [comment]
hey @viral-vora , Thanks for reporting this issue, we have fixed it in the latest [0.0.2](https://pypi.org/project/applepassgenerator/0.0.2/) release 🚀

**Comment by viral-vora** [comment]
Do you have anything similar for generating Google Wallet passes?

**Comment by vaibhav-pdgt** [comment]
> 

No, we haven't explored Google Wallet Passes yet.

**Comment by viral-vora** [comment]
Ok, Thank you.
